Task: unified-face-model
scorer: DLC_resnet50
date: '2026-01-01'
multianimalproject: false
identity: null
project_path: /Users/howardwang/Desktop/PhD Application/Interviews/CSHL/Helen Hou/monkey_behavior_cheese3d_gui/model/unified-face-model/backend/unified-face-model-DLC_resnet50-2026-01-01
engine: pytorch
video_sets:
  ? /Users/howardwang/Desktop/Ruten/Evaluation-Metrics_Vishal-main/Face Video copy/2025-05-28_14-21-30_062244/cam-bottomleft.mp4
  : crop: 0, 600, 0, 600
  ? /Users/howardwang/Desktop/Ruten/Evaluation-Metrics_Vishal-main/Face Video copy/2025-05-28_14-21-30_062244/cam-bottomright.mp4
  : crop: 0, 600, 0, 600
  /Users/howardwang/Desktop/Ruten/Evaluation-Metrics_Vishal-main/Face Video copy/2025-05-28_14-21-30_062244/cam-topleft.mp4:
    crop: 0, 600, 0, 600
  /Users/howardwang/Desktop/Ruten/Evaluation-Metrics_Vishal-main/Face Video copy/2025-05-28_14-21-30_062244/cam-topright.mp4:
    crop: 0, 600, 0, 600
start: 0
stop: 1
numframes2pick: 20
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.6
colormap: rainbow
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
detector_snapshotindex: -1
batch_size: 8
detector_batch_size: 1
cropping: false
x1: 0
x2: 640
y1: 277
y2: 624
corner2move2:
- 50
- 50
move2corner: true
SuperAnimalConversionTables: null
bodyparts:
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10'
- '11'
